name: PHP Linter

on:
  push:
    branches:
      - main
      - '*'
  
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check PHP syntax errors
      uses: overtrue/phplint@3.0.3
      with:
        path: .
        options: --json=./annotations.json
    - name: Annotate
      uses: yuzutech/annotations-action@v0.4.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title: 'lint'
        input: './annotations.json'
