name: Generate installable plugin zip, and upload as release asset
on:
  release:
    types: [published]
jobs:
  build:
    name: prepare and upload release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build project
        run: |
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/graphql-api.zip . -x *.git* node_modules/\* .* "*/\.*" *.md *.dist composer.* dev-helpers** build**
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: graphql-api
            path: "build/${{ github.event.repository.name }}.zip"
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: "build/${{ github.event.repository.name }}.zip application/zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
