name: Deploy to WordPress.org
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@v0.0.5
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}